In [ ]:
import os
import json
import pandas as pd
import numpy as np

from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional

print("Environment ready!")

Environment ready!

In [ ]:
from google.colab import userdata

OPENAI_API_KEY = userdata.get("OPENAI_API_KEY")

if not OPENAI_API_KEY:
    raise ValueError(
        "OPENAI_API_KEY not found. "
        "Add it to Colab Secrets before continuing."
    )

os.environ["OPENAI_API_KEY"] = OPENAI_API_KEY

print("OpenAI API key loaded successfully.")

OpenAI API key loaded successfully.

In [ ]:
!pip -q install -U openai

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.7/41.7 kB 2.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 28.5 MB/s eta 0:00:00

In [ ]:
from openai import OpenAI

client = OpenAI(api_key=os.environ["OPENAI_API_KEY"])

print("OpenAI client initialized.")

OpenAI client initialized.

In [ ]:
response = client.responses.create(
    model="gpt-4.1-mini",
    input="In one sentence, define an AI agent."
)

print(response.output_text)

An AI agent is a system that perceives its environment through sensors and acts upon it using actuators to achieve specific goals.

In [ ]:
customers = pd.DataFrame([
    {
        "customer_id": "C001",
        "name": "Aarav",
        "tenure_months": 36,
        "monthly_spend": 4200,
        "orders_last_90d": 8,
        "days_since_last_order": 12,
        "support_tickets": 1,
        "discount_usage_pct": 20
    },
    {
        "customer_id": "C002",
        "name": "Diya",
        "tenure_months": 8,
        "monthly_spend": 1800,
        "orders_last_90d": 2,
        "days_since_last_order": 67,
        "support_tickets": 5,
        "discount_usage_pct": 85
    },
    {
        "customer_id": "C003",
        "name": "Kabir",
        "tenure_months": 18,
        "monthly_spend": 3100,
        "orders_last_90d": 5,
        "days_since_last_order": 24,
        "support_tickets": 2,
        "discount_usage_pct": 40
    },
    {
        "customer_id": "C004",
        "name": "Meera",
        "tenure_months": 5,
        "monthly_spend": 950,
        "orders_last_90d": 1,
        "days_since_last_order": 92,
        "support_tickets": 7,
        "discount_usage_pct": 95
    },
    {
        "customer_id": "C005",
        "name": "Rohan",
        "tenure_months": 48,
        "monthly_spend": 5600,
        "orders_last_90d": 10,
        "days_since_last_order": 7,
        "support_tickets": 0,
        "discount_usage_pct": 10
    },
    {
        "customer_id": "C006",
        "name": "Ananya",
        "tenure_months": 14,
        "monthly_spend": 2200,
        "orders_last_90d": 3,
        "days_since_last_order": 48,
        "support_tickets": 4,
        "discount_usage_pct": 70
    }
])

customers

,customer_id,name,tenure_months,monthly_spend,orders_last_90d,days_since_last_order,support_tickets,discount_usage_pct
0,C001,Aarav,36,4200,8,12,1,20
1,C002,Diya,8,1800,2,67,5,85
2,C003,Kabir,18,3100,5,24,2,40
3,C004,Meera,5,950,1,92,7,95
4,C005,Rohan,48,5600,10,7,0,10
5,C006,Ananya,14,2200,3,48,4,70

In [ ]:
print("Shape:", customers.shape)

print("\nColumns:")
print(customers.columns.tolist())

print("\nBasic statistics:")
display(customers.describe())

print("\nMissing values:")
display(customers.isnull().sum())

Shape: (6, 8)

Columns:
['customer_id', 'name', 'tenure_months', 'monthly_spend', 'orders_last_90d', 'days_since_last_order', 'support_tickets', 'discount_usage_pct']

Basic statistics:

,tenure_months,monthly_spend,orders_last_90d,days_since_last_order,support_tickets,discount_usage_pct
count,6.000000,6.000000,6.000000,6.000000,6.000000,6.000000
mean,21.500000,2975.000000,4.833333,41.666667,3.166667,53.333333
std,16.944025,1702.277886,3.544949,33.494278,2.639444,35.166272
min,5.000000,950.000000,1.000000,7.000000,0.000000,10.000000
25%,9.500000,1900.000000,2.250000,15.000000,1.250000,25.000000
50%,16.000000,2650.000000,4.000000,36.000000,3.000000,55.000000
75%,31.500000,3925.000000,7.250000,62.250000,4.750000,81.250000
max,48.000000,5600.000000,10.000000,92.000000,7.000000,95.000000

Missing values:

customer_id              0
name                     0
tenure_months            0
monthly_spend            0
orders_last_90d          0
days_since_last_order    0
support_tickets          0
discount_usage_pct       0
dtype: int64

In [ ]:
customer_context = customers.to_dict(orient="records")

prompt = f"""
You are a retail customer analytics assistant.

Here is the customer dataset:

{json.dumps(customer_context, indent=2)}

Business question:
Identify customers who appear to be at higher risk of churn
and briefly explain why.
"""

response = client.responses.create(
    model="gpt-4.1-mini",
    input=prompt
)

print(response.output_text)

Based on the dataset, the customers at higher risk of churn are likely:

1. **Meera (C004)**
   - Very low tenure (5 months)
   - Very low monthly spend (950)
   - Only 1 order in the last 90 days
   - Long duration since last order (92 days)
   - Highest number of support tickets (7)
   - Very high discount usage (95%)
   - Explanation: Low purchase frequency combined with high support issues and long inactivity period indicate a high churn risk.

2. **Diya (C002)**
   - Low tenure (8 months)
   - Relatively low monthly spend (1800)
   - Only 2 orders in the last 90 days
   - High days since last order (67 days)
   - Several support tickets (5)
   - Very high discount usage (85%)
   - Explanation: Limited recent activity, support issues, and dependence on discounts suggest potential dissatisfaction or decreased loyalty.

3. **Ananya (C006)**
   - Moderate tenure (14 months)
   - Moderate spend (2200)
   - Low orders in the last 90 days (3)
   - Moderate days since last order (48 days)
   - 4 support tickets
   - High discount usage (70%)
   - Explanation: Moderate engagement but relatively high support issues and discount reliance may signal risk if trends continue downward.

---

**Summary:**
Customers with low order frequency, extended inactivity, high support interactions, and heavy use of discounts (especially Meera, Diya, and Ananya) indicate higher churn risk compared to others like Aarav and Rohan, who show frequent purchases and low support tickets.

In [ ]:
@dataclass
class AgentState:
    user_goal: str
    execution_history: List[Dict[str, Any]] = field(default_factory=list)
    observations: List[str] = field(default_factory=list)
    reasoning_outputs: List[str] = field(default_factory=list)
    tool_responses: List[Dict[str, Any]] = field(default_factory=list)
    final_outcome: Optional[str] = None
    iteration: int = 0
    status: str = "RUNNING"

In [ ]:
state = AgentState(
    user_goal=(
        "Identify customers who appear to be at high risk of churn "
        "and recommend an appropriate business action."
    )
)

state

AgentState(user_goal='Identify customers who appear to be at high risk of churn and recommend an appropriate business action.', execution_history=[], observations=[], reasoning_outputs=[], tool_responses=[], final_outcome=None, iteration=0, status='RUNNING')

In [ ]:
def display_state(state: AgentState):
    print("=" * 70)
    print(f"ITERATION : {state.iteration}")
    print(f"STATUS    : {state.status}")
    print(f"GOAL      : {state.user_goal}")

    print("\nOBSERVATIONS:")
    for item in state.observations:
        print(" -", item)

    print("\nHISTORY:")
    for item in state.execution_history:
        print(" -", item)

    print("\nFINAL OUTCOME:")
    print(state.final_outcome)

    print("=" * 70)


display_state(state)

======================================================================
ITERATION : 0
STATUS    : RUNNING
GOAL      : Identify customers who appear to be at high risk of churn and recommend an appropriate business action.

OBSERVATIONS:

HISTORY:

FINAL OUTCOME:
None
======================================================================

In [ ]:
dataset_summary = customers[
    [
        "customer_id",
        "name",
        "monthly_spend",
        "orders_last_90d",
        "days_since_last_order",
        "support_tickets",
        "discount_usage_pct"
    ]
].to_dict(orient="records")

state.observations.append(
    "Customer dataset is available for analysis."
)

state.execution_history.append({
    "iteration": state.iteration,
    "action": "OBSERVE_DATASET",
    "result": f"Loaded {len(dataset_summary)} customer records."
})

display_state(state)

======================================================================
ITERATION : 0
STATUS    : RUNNING
GOAL      : Identify customers who appear to be at high risk of churn and recommend an appropriate business action.

OBSERVATIONS:
 - Customer dataset is available for analysis.

HISTORY:
 - {'iteration': 0, 'action': 'OBSERVE_DATASET', 'result': 'Loaded 6 customer records.'}

FINAL OUTCOME:
None
======================================================================

In [ ]:
def build_reasoning_prompt(state: AgentState) -> str:
    return f"""
You are the reasoning component of a retail customer intelligence agent.

USER GOAL:
{state.user_goal}

CURRENT ITERATION:
{state.iteration}

OBSERVATIONS:
{json.dumps(state.observations, indent=2)}

EXECUTION HISTORY:
{json.dumps(state.execution_history, indent=2)}

CUSTOMER DATA:
{json.dumps(dataset_summary, indent=2)}

Your task:

1. Analyse the current state.
2. Determine what should happen next.
3. Decide whether the business goal has been achieved.

Respond with exactly this structure:

NEXT_ACTION: <describe the next action>
GOAL_COMPLETE: <YES or NO>
OUTCOME: <short explanation>
"""

In [ ]:
def reason(state: AgentState) -> str:

    prompt = build_reasoning_prompt(state)

    response = client.responses.create(
        model="gpt-4.1-mini",
        input=prompt
    )

    reasoning = response.output_text

    state.reasoning_outputs.append(reasoning)

    return reasoning


reasoning = reason(state)

print(reasoning)

NEXT_ACTION: Analyze customer data to identify high churn risk indicators such as low orders, high days since last order, many support tickets, and high discount usage percentage, then segment the customers accordingly.
GOAL_COMPLETE: NO
OUTCOME: Initial data is loaded; next step is detailed analysis to identify which customers are at high risk of churn.

In [ ]:
def parse_decision(reasoning: str) -> Dict[str, str]:

    decision = {
        "next_action": "",
        "goal_complete": "",
        "outcome": ""
    }

    for line in reasoning.splitlines():

        if line.startswith("NEXT_ACTION:"):
            decision["next_action"] = line.replace(
                "NEXT_ACTION:", ""
            ).strip()

        elif line.startswith("GOAL_COMPLETE:"):
            decision["goal_complete"] = line.replace(
                "GOAL_COMPLETE:", ""
            ).strip().upper()

        elif line.startswith("OUTCOME:"):
            decision["outcome"] = line.replace(
                "OUTCOME:", ""
            ).strip()

    return decision


decision = parse_decision(reasoning)

decision

{'next_action': 'Analyze customer data to identify high churn risk indicators such as low orders, high days since last order, many support tickets, and high discount usage percentage, then segment the customers accordingly.',
 'goal_complete': 'NO',
 'outcome': 'Initial data is loaded; next step is detailed analysis to identify which customers are at high risk of churn.'}

In [ ]:
def act(state: AgentState, decision: Dict[str, str]):

    state.execution_history.append({
        "iteration": state.iteration,
        "action": decision["next_action"],
        "result": decision["outcome"]
    })

    state.observations.append(
        f"Agent decided: {decision['next_action']}"
    )

    if decision["goal_complete"] == "YES":
        state.final_outcome = decision["outcome"]
        state.status = "COMPLETED"


act(state, decision)

display_state(state)

======================================================================
ITERATION : 0
STATUS    : RUNNING
GOAL      : Identify customers who appear to be at high risk of churn and recommend an appropriate business action.

OBSERVATIONS:
 - Customer dataset is available for analysis.
 - Agent decided: Analyze customer data to identify high churn risk indicators such as low orders, high days since last order, many support tickets, and high discount usage percentage, then segment the customers accordingly.

HISTORY:
 - {'iteration': 0, 'action': 'OBSERVE_DATASET', 'result': 'Loaded 6 customer records.'}
 - {'iteration': 0, 'action': 'Analyze customer data to identify high churn risk indicators such as low orders, high days since last order, many support tickets, and high discount usage percentage, then segment the customers accordingly.', 'result': 'Initial data is loaded; next step is detailed analysis to identify which customers are at high risk of churn.'}

FINAL OUTCOME:
None
======================================================================

In [ ]:
state.iteration += 1

display_state(state)

======================================================================
ITERATION : 1
STATUS    : RUNNING
GOAL      : Identify customers who appear to be at high risk of churn and recommend an appropriate business action.

OBSERVATIONS:
 - Customer dataset is available for analysis.
 - Agent decided: Analyze customer data to identify high churn risk indicators such as low orders, high days since last order, many support tickets, and high discount usage percentage, then segment the customers accordingly.

HISTORY:
 - {'iteration': 0, 'action': 'OBSERVE_DATASET', 'result': 'Loaded 6 customer records.'}
 - {'iteration': 0, 'action': 'Analyze customer data to identify high churn risk indicators such as low orders, high days since last order, many support tickets, and high discount usage percentage, then segment the customers accordingly.', 'result': 'Initial data is loaded; next step is detailed analysis to identify which customers are at high risk of churn.'}

FINAL OUTCOME:
None
======================================================================

In [ ]:
def run_agent_once(state: AgentState):

    print(f"\n--- ITERATION {state.iteration} ---")

    # OBSERVE
    print("1. OBSERVE")

    # REASON
    print("2. REASON")
    reasoning = reason(state)

    # DECIDE
    print("3. DECIDE")
    decision = parse_decision(reasoning)
    print("Decision:", decision)

    # ACT
    print("4. ACT")
    act(state, decision)

    # UPDATE
    print("5. UPDATE STATE")
    state.iteration += 1

    return state

In [ ]:
state = AgentState(
    user_goal=(
        "Identify customers who appear to be at high risk of churn "
        "and recommend an appropriate business action."
    )
)

state.observations.append(
    f"Customer dataset contains {len(customers)} records."
)

state = run_agent_once(state)

display_state(state)

--- ITERATION 0 ---
1. OBSERVE
2. REASON
3. DECIDE
Decision: {'next_action': 'Identify customers with indicators of high churn risk based on metrics such as high days since last order, high number of support tickets, high discount usage, and low order frequency. Then recommend personalized retention actions such as targeted offers, improved customer support, or engagement campaigns for those customers.', 'goal_complete': 'NO', 'outcome': 'The customer data has been reviewed, but high-risk customers have not yet been clearly identified or prescribed retention strategies, so the goal to identify high-risk customers and recommend business actions is not yet complete.'}
4. ACT
5. UPDATE STATE
======================================================================
ITERATION : 1
STATUS    : RUNNING
GOAL      : Identify customers who appear to be at high risk of churn and recommend an appropriate business action.

OBSERVATIONS:
 - Customer dataset contains 6 records.
 - Agent decided: Identify customers with indicators of high churn risk based on metrics such as high days since last order, high number of support tickets, high discount usage, and low order frequency. Then recommend personalized retention actions such as targeted offers, improved customer support, or engagement campaigns for those customers.

HISTORY:
 - {'iteration': 0, 'action': 'Identify customers with indicators of high churn risk based on metrics such as high days since last order, high number of support tickets, high discount usage, and low order frequency. Then recommend personalized retention actions such as targeted offers, improved customer support, or engagement campaigns for those customers.', 'result': 'The customer data has been reviewed, but high-risk customers have not yet been clearly identified or prescribed retention strategies, so the goal to identify high-risk customers and recommend business actions is not yet complete.'}

FINAL OUTCOME:
None
======================================================================

In [ ]:
def run_agent(state: AgentState, max_iterations: int = 3):

    while (
        state.status == "RUNNING"
        and state.iteration < max_iterations
    ):

        state = run_agent_once(state)

        print("\nCurrent status:", state.status)

    return state

In [ ]:
state = AgentState(
    user_goal=(
        "Identify customers who appear to be at high risk of churn "
        "and recommend an appropriate business action."
    )
)

state.observations.append(
    f"Customer dataset contains {len(customers)} records."
)

final_state = run_agent(
    state,
    max_iterations=3
)

display_state(final_state)

--- ITERATION 0 ---
1. OBSERVE
2. REASON
3. DECIDE
Decision: {'next_action': 'Identify customers with high churn risk based on indicators such as long days since last order (e.g., >60 days), high number of support tickets (>3), and high discount usage (>70%). Then recommend targeted retention actions such as personalized offers or improved customer support outreach for these customers.', 'goal_complete': 'NO', 'outcome': 'The customer dataset is analyzed, but high-risk customers have not yet been identified or targeted actions recommended. Further analysis and action planning are needed to achieve the goal.'}
4. ACT
5. UPDATE STATE

Current status: RUNNING

--- ITERATION 1 ---
1. OBSERVE
2. REASON
3. DECIDE
Decision: {'next_action': 'Identify customers meeting the high churn risk criteria (days since last order >60, support tickets >3, discount usage >70%), list them explicitly, and recommend specific targeted retention actions such as personalized offers or improved support outreach to reduce churn risk.', 'goal_complete': 'NO', 'outcome': 'The current analysis has identified the criteria and reviewed customer data but has not yet explicitly flagged high-risk customers or recommended retention actions for them. Further steps are needed to meet the user goal.'}
4. ACT
5. UPDATE STATE

Current status: RUNNING

--- ITERATION 2 ---
1. OBSERVE
2. REASON
3. DECIDE
Decision: {'next_action': 'Explicitly flag customers meeting all high churn risk criteria (days since last order >60, support tickets >3, discount usage >70%) from the dataset, list them, and provide specific targeted retention actions such as personalized offers or improved customer support outreach for each flagged customer.', 'goal_complete': 'NO', 'outcome': 'The criteria for high churn risk have been defined and reviewed with customer data, but no customers have yet been explicitly identified or listed as high risk, nor have any retention actions been recommended.'}
4. ACT
5. UPDATE STATE

Current status: RUNNING
======================================================================
ITERATION : 3
STATUS    : RUNNING
GOAL      : Identify customers who appear to be at high risk of churn and recommend an appropriate business action.

OBSERVATIONS:
 - Customer dataset contains 6 records.
 - Agent decided: Identify customers with high churn risk based on indicators such as long days since last order (e.g., >60 days), high number of support tickets (>3), and high discount usage (>70%). Then recommend targeted retention actions such as personalized offers or improved customer support outreach for these customers.
 - Agent decided: Identify customers meeting the high churn risk criteria (days since last order >60, support tickets >3, discount usage >70%), list them explicitly, and recommend specific targeted retention actions such as personalized offers or improved support outreach to reduce churn risk.
 - Agent decided: Explicitly flag customers meeting all high churn risk criteria (days since last order >60, support tickets >3, discount usage >70%) from the dataset, list them, and provide specific targeted retention actions such as personalized offers or improved customer support outreach for each flagged customer.

HISTORY:
 - {'iteration': 0, 'action': 'Identify customers with high churn risk based on indicators such as long days since last order (e.g., >60 days), high number of support tickets (>3), and high discount usage (>70%). Then recommend targeted retention actions such as personalized offers or improved customer support outreach for these customers.', 'result': 'The customer dataset is analyzed, but high-risk customers have not yet been identified or targeted actions recommended. Further analysis and action planning are needed to achieve the goal.'}
 - {'iteration': 1, 'action': 'Identify customers meeting the high churn risk criteria (days since last order >60, support tickets >3, discount usage >70%), list them explicitly, and recommend specific targeted retention actions such as personalized offers or improved support outreach to reduce churn risk.', 'result': 'The current analysis has identified the criteria and reviewed customer data but has not yet explicitly flagged high-risk customers or recommended retention actions for them. Further steps are needed to meet the user goal.'}
 - {'iteration': 2, 'action': 'Explicitly flag customers meeting all high churn risk criteria (days since last order >60, support tickets >3, discount usage >70%) from the dataset, list them, and provide specific targeted retention actions such as personalized offers or improved customer support outreach for each flagged customer.', 'result': 'The criteria for high churn risk have been defined and reviewed with customer data, but no customers have yet been explicitly identified or listed as high risk, nor have any retention actions been recommended.'}

FINAL OUTCOME:
None
======================================================================

In [ ]:
def get_customer(customer_id: str) -> Dict[str, Any]: #Retrieval Tool

    matches = customers[
        customers["customer_id"] == customer_id
    ]

    if matches.empty:
        raise ValueError(
            f"Customer '{customer_id}' was not found."
        )

    return matches.iloc[0].to_dict()

In [ ]:
def get_customer_validated(customer_id: str) -> Dict[str, Any]:

    if not isinstance(customer_id, str):
        raise TypeError(
            "customer_id must be a string."
        )

    if not customer_id.strip():
        raise ValueError(
            "customer_id cannot be empty."
        )

    customer_id = customer_id.strip().upper()

    customer = get_customer(customer_id)

    required_fields = [
        "customer_id",
        "name",
        "monthly_spend",
        "orders_last_90d",
        "days_since_last_order",
        "support_tickets",
        "discount_usage_pct"
    ]

    missing = [
        field for field in required_fields
        if field not in customer
    ]

    if missing:
        raise ValueError(
            f"Tool response missing fields: {missing}"
        )

    return customer

In [ ]:
def calculate_risk_score(customer: Dict[str, Any]) -> Dict[str, Any]:

    score = 0
    reasons = []

    if customer["days_since_last_order"] > 60:
        score += 40
        reasons.append("Long inactivity period")

    elif customer["days_since_last_order"] > 30:
        score += 25
        reasons.append("Increasing inactivity")

    if customer["orders_last_90d"] <= 2:
        score += 25
        reasons.append("Low recent order frequency")

    if customer["support_tickets"] >= 5:
        score += 20
        reasons.append("High support interaction")

    if customer["discount_usage_pct"] >= 80:
        score += 15
        reasons.append("High discount dependency")

    score = min(score, 100)

    if score >= 60:
        risk_level = "HIGH"
    elif score >= 30:
        risk_level = "MEDIUM"
    else:
        risk_level = "LOW"

    return {
        "customer_id": customer["customer_id"],
        "risk_score": score,
        "risk_level": risk_level,
        "reasons": reasons
    }

In [ ]:
TOOLS = {
    "get_customer": get_customer_validated,
    "calculate_risk": calculate_risk_score
}

TOOLS

{'get_customer': <function __main__.get_customer_validated(customer_id: str) -> Dict[str, Any]>,
 'calculate_risk': <function __main__.calculate_risk_score(customer: Dict[str, Any]) -> Dict[str, Any]>}

In [ ]:
TOOL_DESCRIPTIONS = {
    "get_customer": {
        "description": "Retrieve customer information using customer_id.",
        "parameters": {
            "customer_id": "string"
        }
    },
    "calculate_risk": {
        "description": "Calculate churn risk using retrieved customer information.",
        "parameters": {
            "customer": "object"
        }
    }
}

print(json.dumps(TOOL_DESCRIPTIONS, indent=2))

{
  "get_customer": {
    "description": "Retrieve customer information using customer_id.",
    "parameters": {
      "customer_id": "string"
    }
  },
  "calculate_risk": {
    "description": "Calculate churn risk using retrieved customer information.",
    "parameters": {
      "customer": "object"
    }
  }
}

In [ ]:
def choose_tool(state: AgentState) -> Dict[str, Any]:

    prompt = f"""
You are the decision-making component of a customer intelligence agent.

USER GOAL:
{state.user_goal}

CURRENT STATE:
{json.dumps(state.observations, indent=2)}

AVAILABLE TOOLS:

1. get_customer
   Purpose: Retrieve customer information.
   Input: customer_id

2. calculate_risk
   Purpose: Calculate churn risk.
   Input: customer object

Choose the next tool required.

Return ONLY valid JSON:

{{
    "tool": "<tool name>",
    "arguments": {{...}}
}}
"""

    response = client.responses.create(
        model="gpt-4.1-mini",
        input=prompt
    )

    return json.loads(response.output_text)

In [ ]:
state = AgentState(
    user_goal=(
        "Analyse customer C002 and determine whether "
        "the customer is at high risk of churn."
    )
)

state.observations.append(
    "No customer information has been retrieved yet."
)

tool_decision = choose_tool(state)

print(json.dumps(tool_decision, indent=2))

{
  "tool": "get_customer",
  "arguments": {
    "customer_id": "C002"
  }
}

In [ ]:
TOOL_SCHEMAS = {

    "get_customer": {
        "required": ["customer_id"],#mandatory
        "types": {
            "customer_id": str
        }
    },

    "calculate_risk": {
        "required": ["customer"],
        "types": {
            "customer": dict
        }
    }
}

In [ ]:
def validate_tool_call(
    tool_name: str,
    arguments: Dict[str, Any]
):

    if tool_name not in TOOL_SCHEMAS:
        raise ValueError(
            f"Unknown tool: {tool_name}"
        )

    schema = TOOL_SCHEMAS[tool_name]

    for required_field in schema["required"]:
        if required_field not in arguments:
            raise ValueError(
                f"Missing required parameter: "
                f"{required_field}"
            )

    for field, expected_type in schema["types"].items():

        if field in arguments:
            if not isinstance(
                arguments[field],
                expected_type
            ):
                raise TypeError(
                    f"{field} must be "
                    f"{expected_type.__name__}"
                )

    return True

In [ ]:
def execute_tool(
    tool_name: str,
    arguments: Dict[str, Any]
):

    validate_tool_call(
        tool_name,
        arguments
    )

    if tool_name not in TOOLS:
        raise ValueError(
            f"Tool '{tool_name}' is not registered."
        )

    tool_function = TOOLS[tool_name]

    return tool_function(**arguments)

In [ ]:
result = execute_tool(
    "get_customer",
    {
        "customer_id": "C002"
    }
)

print(json.dumps(result, indent=2))

{
  "customer_id": "C002",
  "name": "Diya",
  "tenure_months": 8,
  "monthly_spend": 1800,
  "orders_last_90d": 2,
  "days_since_last_order": 67,
  "support_tickets": 5,
  "discount_usage_pct": 85
}

In [ ]:
def execute_tool_with_retry(
    tool_name: str,
    arguments: Dict[str, Any],
    max_retries: int = 2
):

    last_error = None

    for attempt in range(1, max_retries + 1):

        try:

            result = execute_tool(
                tool_name,
                arguments
            )

            return {
                "success": True,
                "attempt": attempt,
                "result": result
            }

        except Exception as e:

            last_error = str(e)

            print(
                f"Attempt {attempt} failed: "
                f"{last_error}"
            )

    return {
        "success": False,
        "attempt": max_retries,
        "error": last_error,
        "fallback": (
            "Unable to execute the requested tool. "
            "Return a safe explanation instead."
        )
    }

In [ ]:
result = execute_tool_with_retry(
    "get_customer",
    {},
    max_retries=2
)

print(json.dumps(result, indent=2))

Attempt 1 failed: Missing required parameter: customer_id
Attempt 2 failed: Missing required parameter: customer_id
{
  "success": false,
  "attempt": 2,
  "error": "Missing required parameter: customer_id",
  "fallback": "Unable to execute the requested tool. Return a safe explanation instead."
}

In [ ]:
state = AgentState(
    user_goal=(
        "Analyse customer C002 and determine whether "
        "the customer is at high risk of churn."
    )
)

tool_result = execute_tool_with_retry(
    "get_customer",
    {"customer_id": "C002"}
)

state.tool_responses.append(tool_result)

state.observations.append(
    "Customer C002 information retrieved successfully."
)

state.execution_history.append({
    "iteration": state.iteration,
    "action": "get_customer",
    "tool_result": tool_result
})

display_state(state)

======================================================================
ITERATION : 0
STATUS    : RUNNING
GOAL      : Analyse customer C002 and determine whether the customer is at high risk of churn.

OBSERVATIONS:
 - Customer C002 information retrieved successfully.

HISTORY:
 - {'iteration': 0, 'action': 'get_customer', 'tool_result': {'success': True, 'attempt': 1, 'result': {'customer_id': 'C002', 'name': 'Diya', 'tenure_months': 8, 'monthly_spend': 1800, 'orders_last_90d': 2, 'days_since_last_order': 67, 'support_tickets': 5, 'discount_usage_pct': 85}}}

FINAL OUTCOME:
None
======================================================================

In [ ]:
def customer_analysis_skill(customer_id: str):

    # Step 1 — Retrieve customer
    customer_result = execute_tool_with_retry(
        "get_customer",
        {"customer_id": customer_id}
    )

    if not customer_result["success"]:
        return {
            "success": False,
            "stage": "customer_retrieval",
            "error": customer_result["error"]
        }

    customer = customer_result["result"]

    # Step 2 — Calculate risk
    risk_result = execute_tool_with_retry(
        "calculate_risk",
        {"customer": customer}
    )

    if not risk_result["success"]:
        return {
            "success": False,
            "stage": "risk_calculation",
            "error": risk_result["error"]
        }

    risk = risk_result["result"]

    return {
        "success": True,
        "customer": customer,
        "risk": risk
    }

In [ ]:
analysis = customer_analysis_skill("C002")

print(json.dumps(analysis, indent=2))

{
  "success": true,
  "customer": {
    "customer_id": "C002",
    "name": "Diya",
    "tenure_months": 8,
    "monthly_spend": 1800,
    "orders_last_90d": 2,
    "days_since_last_order": 67,
    "support_tickets": 5,
    "discount_usage_pct": 85
  },
  "risk": {
    "customer_id": "C002",
    "risk_score": 100,
    "risk_level": "HIGH",
    "reasons": [
      "Long inactivity period",
      "Low recent order frequency",
      "High support interaction",
      "High discount dependency"
    ]
  }
}

In [ ]:
def explain_customer_risk(
    customer: Dict[str, Any],
    risk: Dict[str, Any]
) -> str:

    prompt = f"""
You are a retail customer analytics expert.

CUSTOMER:
{json.dumps(customer, indent=2)}

RISK ASSESSMENT:
{json.dumps(risk, indent=2)}

Explain:

1. Why this customer has this risk level.
2. Which factors are most important.
3. What the business should pay attention to.

Keep the explanation concise and business-focused.
"""

    response = client.responses.create(
        model="gpt-4.1-mini",
        input=prompt
    )

    return response.output_text

In [ ]:
if analysis["success"]:

    explanation = explain_customer_risk(
        analysis["customer"],
        analysis["risk"]
    )

    print(explanation)

1. **Risk Level Explanation:**
Diya is classified as HIGH risk due to her long period of inactivity (67 days since last order) combined with low recent order frequency (only 2 orders in the last 90 days). Despite a decent tenure and monthly spend, her frequent use of discounts (85%) suggests she may be price-sensitive or only buying when incentivized. Additionally, a high number of support tickets (5) indicates possible dissatisfaction or unresolved issues, increasing the likelihood of churn.

2. **Most Important Factors:**
- Long inactivity period and low order frequency signal declining engagement.
- High discount dependency points to vulnerability if promotions stop.
- Elevated support interaction hints at potential service-related dissatisfaction.

3. **Business Focus:**
- Address Diya’s support issues promptly to improve satisfaction.
- Develop targeted retention strategies that reduce reliance on discounts, such as personalized offers or loyalty benefits.
- Proactively re-engage with tailored communications before inactivity leads to churn.

In [ ]:
def intervention_recommendation_skill(
    customer: Dict[str, Any],
    risk: Dict[str, Any]
) -> Dict[str, Any]:

    risk_level = risk["risk_level"]

    if risk_level == "HIGH":

        action = "Immediate retention intervention"
        priority = "P1"

    elif risk_level == "MEDIUM":

        action = "Targeted engagement campaign"
        priority = "P2"

    else:

        action = "Continue regular engagement"
        priority = "P3"

    return {
        "customer_id": customer["customer_id"],
        "risk_level": risk_level,
        "recommended_action": action,
        "priority": priority
    }

In [ ]:
recommendation = intervention_recommendation_skill(
    analysis["customer"],
    analysis["risk"]
)

print(json.dumps(recommendation, indent=2))

{
  "customer_id": "C002",
  "risk_level": "HIGH",
  "recommended_action": "Immediate retention intervention",
  "priority": "P1"
}

In [ ]:
def churn_assessment_skill(customer_id: str):

    # STEP 1 — Customer analysis
    analysis = customer_analysis_skill(customer_id)

    if not analysis["success"]:
        return {
            "success": False,
            "stage": "analysis",
            "error": analysis["error"]
        }

    # STEP 2 — Explain risk
    explanation = explain_customer_risk(
        analysis["customer"],
        analysis["risk"]
    )

    # STEP 3 — Generate recommendation
    recommendation = intervention_recommendation_skill(
        analysis["customer"],
        analysis["risk"]
    )

    return {
        "success": True,
        "customer": analysis["customer"],
        "risk": analysis["risk"],
        "explanation": explanation,
        "recommendation": recommendation
    }

In [ ]:
customer_assessment = churn_assessment_skill("C002")

print(
    json.dumps(
        customer_assessment,
        indent=2
    )
)

{
  "success": true,
  "customer": {
    "customer_id": "C002",
    "name": "Diya",
    "tenure_months": 8,
    "monthly_spend": 1800,
    "orders_last_90d": 2,
    "days_since_last_order": 67,
    "support_tickets": 5,
    "discount_usage_pct": 85
  },
  "risk": {
    "customer_id": "C002",
    "risk_score": 100,
    "risk_level": "HIGH",
    "reasons": [
      "Long inactivity period",
      "Low recent order frequency",
      "High support interaction",
      "High discount dependency"
    ]
  },
  "explanation": "1. **Risk Level Explanation:**  \nDiya is classified as a HIGH risk customer because she has not placed an order in the last 67 days despite being an active customer for 8 months. Her order frequency is low (only 2 orders in the last 90 days), signaling reduced engagement. Additionally, she heavily relies on discounts (85% discount usage) and frequently interacts with support (5 tickets), indicating possible dissatisfaction or friction.\n\n2. **Most Important Factors:**  \n- **Long inactivity period (67 days since last order):** Signals potential churn.  \n- **Low recent order frequency (2 orders in last 90 days):** Confirms declining purchase behavior.  \n- **High support tickets (5 tickets):** Highlights unresolved issues or dissatisfaction.  \n- **High discount dependency (85% usage):** Customer is price-sensitive and may not be loyal without incentives.\n\n3. **Business Focus:**  \n- Investigate and resolve underlying customer support issues to improve satisfaction.  \n- Engage the customer proactively with personalized offers beyond discounts to rebuild loyalty.  \n- Monitor future order behavior closely to prevent churn.  \n- Consider value-based retention strategies rather than pure discounting to enhance profitability.",
  "recommendation": {
    "customer_id": "C002",
    "risk_level": "HIGH",
    "recommended_action": "Immediate retention intervention",
    "priority": "P1"
  }
}

In [ ]:
SKILLS = {
    "customer_analysis": customer_analysis_skill,
    "intervention_recommendation": intervention_recommendation_skill,
    "churn_assessment": churn_assessment_skill
}

print("Registered skills:")
for skill_name in SKILLS:
    print(" -", skill_name)

Registered skills:
 - customer_analysis
 - intervention_recommendation
 - churn_assessment

In [ ]:
SKILL_DESCRIPTIONS = {

    "customer_analysis": {
        "description": (
            "Retrieve a customer and calculate their churn risk."
        ),
        "input": {
            "customer_id": "string"
        }
    },

    "intervention_recommendation": {
        "description": (
            "Recommend a business intervention based on risk."
        ),
        "input": {
            "customer": "object",
            "risk": "object"
        }
    },

    "churn_assessment": {
        "description": (
            "Perform end-to-end churn assessment and "
            "recommend a retention action."
        ),
        "input": {
            "customer_id": "string"
        }
    }
}

print(
    json.dumps(
        SKILL_DESCRIPTIONS,
        indent=2
    )
)

{
  "customer_analysis": {
    "description": "Retrieve a customer and calculate their churn risk.",
    "input": {
      "customer_id": "string"
    }
  },
  "intervention_recommendation": {
    "description": "Recommend a business intervention based on risk.",
    "input": {
      "customer": "object",
      "risk": "object"
    }
  },
  "churn_assessment": {
    "description": "Perform end-to-end churn assessment and recommend a retention action.",
    "input": {
      "customer_id": "string"
    }
  }
}

In [ ]:
def choose_skill(user_goal: str) -> Dict[str, Any]:

    prompt = f"""
You are the decision-making component of a retail AI agent.

USER GOAL:
{user_goal}

AVAILABLE SKILLS:

{json.dumps(SKILL_DESCRIPTIONS, indent=2)}

Choose the most appropriate skill.

Return ONLY valid JSON:

{{
    "skill": "<skill name>",
    "arguments": {{...}}
}}
"""

    response = client.responses.create(
        model="gpt-4.1-mini",
        input=prompt
    )

    return json.loads(response.output_text)

In [ ]:
user_goal = """
Assess customer C002 for churn risk and recommend
the appropriate retention action.
"""

skill_decision = choose_skill(user_goal)

print(
    json.dumps(
        skill_decision,
        indent=2
    )
)

{
  "skill": "churn_assessment",
  "arguments": {
    "customer_id": "C002"
  }
}

In [ ]:
selected_skill = skill_decision["skill"]
skill_arguments = skill_decision["arguments"]

if selected_skill not in SKILLS:
    raise ValueError(
        f"Unknown skill: {selected_skill}"
    )

skill_result = SKILLS[selected_skill](
    **skill_arguments
)

print(
    json.dumps(
        skill_result,
        indent=2
    )
)

{
  "success": true,
  "customer": {
    "customer_id": "C002",
    "name": "Diya",
    "tenure_months": 8,
    "monthly_spend": 1800,
    "orders_last_90d": 2,
    "days_since_last_order": 67,
    "support_tickets": 5,
    "discount_usage_pct": 85
  },
  "risk": {
    "customer_id": "C002",
    "risk_score": 100,
    "risk_level": "HIGH",
    "reasons": [
      "Long inactivity period",
      "Low recent order frequency",
      "High support interaction",
      "High discount dependency"
    ]
  },
  "explanation": "1. **Risk Level Explanation**: Diya is classified as a high-risk customer because she has been inactive for 67 days, placing her at risk of churn despite being a relatively recent customer (8 months tenure). Her order frequency has dropped significantly (only 2 orders in the last 90 days), signaling declining engagement. Additionally, her high number of support tickets (5) indicates potential dissatisfaction, and her heavy reliance on discounts (85% usage) suggests price sensitivity and reduced loyalty without promotions.\n\n2. **Most Important Factors**:\n   - **Long inactivity period (67 days since last order)**: Strong indicator of waning interest.\n   - **Low recent order frequency (2 orders/90 days)**: Shows declining purchase behavior.\n   - **High support tickets (5)**: Reflects friction or unresolved issues affecting satisfaction.\n   - **High discount usage (85%)**: Signals dependency on price incentives rather than brand loyalty.\n\n3. **Business Attention**:\n   - Prioritize customer recovery strategies targeting re-engagement through personalized communication and tailored offers to stimulate ordering.\n   - Address support issues proactively to improve customer experience and reduce friction.\n   - Consider evaluating pricing or loyalty programs to reduce discount dependency and foster long-term value.\n   - Monitor similar customers closely to prevent churn and identify root causes early.",
  "recommendation": {
    "customer_id": "C002",
    "risk_level": "HIGH",
    "recommended_action": "Immediate retention intervention",
    "priority": "P1"
  }
}

In [ ]:
state = AgentState(
    user_goal=(
        "Assess customer C002 for churn risk and "
        "recommend an appropriate retention action."
    )
)

state.iteration = 0

state.execution_history.append({
    "iteration": state.iteration,
    "action": "SELECT_SKILL",
    "skill": selected_skill,
    "arguments": skill_arguments
})

state.tool_responses.append({
    "source": "skill",
    "skill": selected_skill,
    "result": skill_result
})

state.observations.append(
    "Churn assessment skill completed."
)

state.final_outcome = (
    skill_result["recommendation"]
    if skill_result["success"]
    else skill_result
)

state.status = "COMPLETED"

display_state(state)

======================================================================
ITERATION : 0
STATUS    : COMPLETED
GOAL      : Assess customer C002 for churn risk and recommend an appropriate retention action.

OBSERVATIONS:
 - Churn assessment skill completed.

HISTORY:
 - {'iteration': 0, 'action': 'SELECT_SKILL', 'skill': 'churn_assessment', 'arguments': {'customer_id': 'C002'}}

FINAL OUTCOME:
{'customer_id': 'C002', 'risk_level': 'HIGH', 'recommended_action': 'Immediate retention intervention', 'priority': 'P1'}
======================================================================

In [ ]:
@dataclass
class TraceEvent:
    iteration: int
    event_type: str
    details: Dict[str, Any]


@dataclass
class AgentTrace:
    events: List[TraceEvent] = field(
        default_factory=list
    )

    def log(
        self,
        iteration: int,
        event_type: str,
        details: Dict[str, Any]
    ):

        self.events.append(
            TraceEvent(
                iteration=iteration,
                event_type=event_type,
                details=details
            )
        )

    def show(self):

        for event in self.events:

            print(
                f"[Iteration {event.iteration}] "
                f"{event.event_type}"
            )

            print(
                json.dumps(
                    event.details,
                    indent=2
                )
            )

            print("-" * 60)

In [ ]:
def check_goal_completion(
    state: AgentState
) -> bool:

    if not state.final_outcome:
        return False

    outcome_text = state.final_outcome.lower()

    required_terms = [
        "risk",
        "recommend"
    ]

    return all(
        term in outcome_text
        for term in required_terms
    )

In [ ]:
def should_terminate(
    state: AgentState,
    max_steps: int = 6
) -> bool:

    # Condition 1: explicit completion
    if state.status == "COMPLETED":
        return True

    # Condition 2: goal achieved
    if check_goal_completion(state):
        state.status = "COMPLETED"
        return True

    # Condition 3: step limit
    if state.iteration >= max_steps:
        state.status = "MAX_STEPS_REACHED"
        return True

    # Condition 4: unrecoverable failure
    if state.status == "FAILED":
        return True

    return False

In [ ]:
def generate_business_response(
    assessment: Dict[str, Any]
) -> str:

    if not assessment["success"]:
        return (
            "The customer assessment could not be completed. "
            f"Reason: {assessment['error']}"
        )

    customer = assessment["customer"]
    risk = assessment["risk"]
    recommendation = assessment["recommendation"]

    return f"""
Customer: {customer['name']} ({customer['customer_id']})

Churn Risk: {risk['risk_level']}
Risk Score: {risk['risk_score']}/100

Key Risk Factors:
- {"; ".join(risk['reasons'])}

Recommendation:
{recommendation['recommended_action']}

Priority:
{recommendation['priority']}
"""

In [ ]:
def reflect_on_result(
    user_goal: str,
    result: str
) -> Dict[str, Any]:

    prompt = f"""
You are a quality-control component for an AI agent.

USER GOAL:
{user_goal}

AGENT RESULT:
{result}

Evaluate whether the result adequately satisfies the goal.

Return ONLY JSON:

{{
    "approved": true or false,
    "issues": ["issue 1", "issue 2"],
    "correction": "what should be improved"
}}
"""

    response = client.responses.create(
        model="gpt-4.1-mini",
        input=prompt
    )

    return json.loads(response.output_text)

In [ ]:
def correct_result(
    user_goal: str,
    result: str,
    reflection: Dict[str, Any]
) -> str:

    prompt = f"""
Improve the following agent result.

USER GOAL:
{user_goal}

CURRENT RESULT:
{result}

QUALITY REVIEW:
{json.dumps(reflection, indent=2)}

Produce a corrected business response.
"""

    response = client.responses.create(
        model="gpt-4.1-mini",
        input=prompt
    )

    return response.output_text

In [ ]:
def run_agent(user_goal: str, max_steps: int = 6):

    # ============================================================
    # 1. INITIALIZE AGENT STATE
    # ============================================================

    state = AgentState(
        user_goal=user_goal
    )

    trace = AgentTrace()

    trace.log(
        0,
        "AGENT_START",
        {
            "goal": user_goal
        }
    )

    # ============================================================
    # 2. AGENT LOOP
    # ============================================================

    while not should_terminate(
        state,
        max_steps=max_steps
    ):

        iteration = state.iteration

        # --------------------------------------------------------
        # OBSERVE
        # --------------------------------------------------------

        observation = {
            "goal": state.user_goal,
            "history": state.execution_history[-3:],
            "tool_results": state.tool_responses[-3:],
            "observations": state.observations[-3:]
        }

        trace.log(
            iteration,
            "OBSERVE",
            observation
        )

        # --------------------------------------------------------
        # REASON + DECIDE
        # --------------------------------------------------------

        decision = choose_skill(
            state.user_goal
        )

        trace.log(
            iteration,
            "DECIDE",
            decision
        )

        state.execution_history.append({
            "iteration": iteration,
            "action": "SELECT_SKILL",
            "decision": decision
        })

        # --------------------------------------------------------
        # VALIDATE DECISION
        # --------------------------------------------------------

        selected_skill = decision.get("skill")
        skill_arguments = decision.get(
            "arguments",
            {}
        )

        if selected_skill not in SKILLS:

            trace.log(
                iteration,
                "INVALID_SKILL",
                {
                    "skill": selected_skill
                }
            )

            state.status = "FAILED"

            break

        # --------------------------------------------------------
        # ACT — EXECUTE SKILL
        # --------------------------------------------------------

        trace.log(
            iteration,
            "SKILL_START",
            {
                "skill": selected_skill,
                "arguments": skill_arguments
            }
        )

        try:

            skill_result = SKILLS[selected_skill](
                **skill_arguments
            )

        except Exception as e:

            trace.log(
                iteration,
                "SKILL_ERROR",
                {
                    "skill": selected_skill,
                    "error": str(e)
                }
            )

            state.status = "FAILED"

            break

        # --------------------------------------------------------
        # UPDATE STATE
        # --------------------------------------------------------

        state.tool_responses.append(
            skill_result
        )

        state.observations.append(
            f"Skill '{selected_skill}' completed."
        )

        state.execution_history.append({
            "iteration": iteration,
            "action": "EXECUTE_SKILL",
            "skill": selected_skill,
            "result": skill_result
        })

        trace.log(
            iteration,
            "SKILL_RESULT",
            {
                "skill": selected_skill,
                "success": skill_result.get(
                    "success",
                    False
                )
            }
        )

        # --------------------------------------------------------
        # GENERATE PROVISIONAL ANSWER
        # --------------------------------------------------------

        if skill_result.get("success"):

            provisional_answer = (
                generate_business_response(
                    skill_result
                )
            )

            state.final_outcome = (
                provisional_answer
            )

        else:

            state.final_outcome = (
                f"Skill failed: "
                f"{skill_result.get('error')}"
            )

        # --------------------------------------------------------
        # REFLECTION / QUALITY CHECK
        # --------------------------------------------------------

        reflection = reflect_on_result(
            user_goal=state.user_goal,
            result=state.final_outcome
        )

        trace.log(
            iteration,
            "REFLECTION",
            reflection
        )

        # --------------------------------------------------------
        # SELF-CORRECTION
        # --------------------------------------------------------

        if not reflection["approved"]:

            trace.log(
                iteration,
                "SELF_CORRECTION",
                {
                    "issues": reflection["issues"]
                }
            )

            corrected_answer = correct_result(
                user_goal=state.user_goal,
                result=state.final_outcome,
                reflection=reflection
            )

            state.final_outcome = (
                corrected_answer
            )

            state.observations.append(
                "Agent performed self-correction."
            )

        # --------------------------------------------------------
        # GOAL COMPLETION CHECK
        # --------------------------------------------------------

        if check_goal_completion(state):

            state.status = "COMPLETED"

            trace.log(
                iteration,
                "GOAL_COMPLETED",
                {
                    "outcome": state.final_outcome
                }
            )

        else:

            state.iteration += 1

            trace.log(
                iteration,
                "GOAL_NOT_COMPLETED",
                {
                    "next_iteration":
                        state.iteration
                }
            )

    # ============================================================
    # 3. FINAL TERMINATION
    # ============================================================

    if state.status != "COMPLETED":

        if state.iteration >= max_steps:

            state.status = "MAX_STEPS_REACHED"

            trace.log(
                state.iteration,
                "TERMINATED",
                {
                    "reason": "Maximum step limit reached."
                }
            )

        elif state.status != "FAILED":

            state.status = "TERMINATED"

            trace.log(
                state.iteration,
                "TERMINATED",
                {
                    "reason":
                        "Agent termination condition reached."
                }
            )

    # ============================================================
    # 4. FINAL TRACE
    # ============================================================

    trace.log(
        state.iteration,
        "AGENT_END",
        {
            "status": state.status
        }
    )

    return {
        "status": state.status,
        "answer": state.final_outcome,
        "state": state,
        "trace": trace
    }

In [ ]:
result = run_agent(
    """
    Assess customer C002 for churn risk,
    explain the major risk factors,
    and recommend the most appropriate
    retention action.
    """
)

In [ ]:
result

{'status': 'COMPLETED',
 'answer': '\nCustomer: Diya (C002)\n\nChurn Risk: HIGH\nRisk Score: 100/100\n\nKey Risk Factors:\n- Long inactivity period; Low recent order frequency; High support interaction; High discount dependency\n\nRecommendation:\nImmediate retention intervention\n\nPriority:\nP1\n',
 'state': AgentState(user_goal='\n    Assess customer C002 for churn risk,\n    explain the major risk factors,\n    and recommend the most appropriate\n    retention action.\n    ', execution_history=[{'iteration': 0, 'action': 'SELECT_SKILL', 'decision': {'skill': 'churn_assessment', 'arguments': {'customer_id': 'C002'}}}, {'iteration': 0, 'action': 'EXECUTE_SKILL', 'skill': 'churn_assessment', 'result': {'success': True, 'customer': {'customer_id': 'C002', 'name': 'Diya', 'tenure_months': 8, 'monthly_spend': 1800, 'orders_last_90d': 2, 'days_since_last_order': 67, 'support_tickets': 5, 'discount_usage_pct': 85}, 'risk': {'customer_id': 'C002', 'risk_score': 100, 'risk_level': 'HIGH', 'reasons': ['Long inactivity period', 'Low recent order frequency', 'High support interaction', 'High discount dependency']}, 'explanation': '1. This customer is classified as HIGH risk because they have not ordered in over two months (67 days), which is a long inactivity period given their previous engagement, and have made only 2 orders in the last 90 days. Despite this, they have submitted a high number of support tickets (5), indicating potential dissatisfaction or unresolved issues. Additionally, their very high discount usage (85%) signals strong dependency on promotions to make purchases.\n\n2. The most important factors driving this risk level are:\n   - Long inactivity period and low recent order frequency, suggesting the customer may be disengaging.\n   - High support tickets, which often correlate with poor customer experience.\n   - High discount dependency, increasing the risk of reduced profitability and potential churn if discounts are removed.\n\n3. The business should focus on:\n   - Proactively reaching out to address potential service issues highlighted by the support tickets.\n   - Designing engagement strategies to reactivate the customer, such as personalized offers or value-added services that do not rely only on discounts.\n   - Monitoring future purchasing behavior closely to intervene before the customer churns.', 'recommendation': {'customer_id': 'C002', 'risk_level': 'HIGH', 'recommended_action': 'Immediate retention intervention', 'priority': 'P1'}}}], observations=["Skill 'churn_assessment' completed."], reasoning_outputs=[], tool_responses=[{'success': True, 'customer': {'customer_id': 'C002', 'name': 'Diya', 'tenure_months': 8, 'monthly_spend': 1800, 'orders_last_90d': 2, 'days_since_last_order': 67, 'support_tickets': 5, 'discount_usage_pct': 85}, 'risk': {'customer_id': 'C002', 'risk_score': 100, 'risk_level': 'HIGH', 'reasons': ['Long inactivity period', 'Low recent order frequency', 'High support interaction', 'High discount dependency']}, 'explanation': '1. This customer is classified as HIGH risk because they have not ordered in over two months (67 days), which is a long inactivity period given their previous engagement, and have made only 2 orders in the last 90 days. Despite this, they have submitted a high number of support tickets (5), indicating potential dissatisfaction or unresolved issues. Additionally, their very high discount usage (85%) signals strong dependency on promotions to make purchases.\n\n2. The most important factors driving this risk level are:\n   - Long inactivity period and low recent order frequency, suggesting the customer may be disengaging.\n   - High support tickets, which often correlate with poor customer experience.\n   - High discount dependency, increasing the risk of reduced profitability and potential churn if discounts are removed.\n\n3. The business should focus on:\n   - Proactively reaching out to address potential service issues highlighted by the support tickets.\n   - Designing engagement strategies to reactivate the customer, such as personalized offers or value-added services that do not rely only on discounts.\n   - Monitoring future purchasing behavior closely to intervene before the customer churns.', 'recommendation': {'customer_id': 'C002', 'risk_level': 'HIGH', 'recommended_action': 'Immediate retention intervention', 'priority': 'P1'}}], final_outcome='\nCustomer: Diya (C002)\n\nChurn Risk: HIGH\nRisk Score: 100/100\n\nKey Risk Factors:\n- Long inactivity period; Low recent order frequency; High support interaction; High discount dependency\n\nRecommendation:\nImmediate retention intervention\n\nPriority:\nP1\n', iteration=0, status='COMPLETED'),
 'trace': AgentTrace(events=[TraceEvent(iteration=0, event_type='AGENT_START', details={'goal': '\n    Assess customer C002 for churn risk,\n    explain the major risk factors,\n    and recommend the most appropriate\n    retention action.\n    '}), TraceEvent(iteration=0, event_type='OBSERVE', details={'goal': '\n    Assess customer C002 for churn risk,\n    explain the major risk factors,\n    and recommend the most appropriate\n    retention action.\n    ', 'history': [], 'tool_results': [], 'observations': []}), TraceEvent(iteration=0, event_type='DECIDE', details={'skill': 'churn_assessment', 'arguments': {'customer_id': 'C002'}}), TraceEvent(iteration=0, event_type='SKILL_START', details={'skill': 'churn_assessment', 'arguments': {'customer_id': 'C002'}}), TraceEvent(iteration=0, event_type='SKILL_RESULT', details={'skill': 'churn_assessment', 'success': True}), TraceEvent(iteration=0, event_type='REFLECTION', details={'approved': True, 'issues': [], 'correction': ''}), TraceEvent(iteration=0, event_type='GOAL_COMPLETED', details={'outcome': '\nCustomer: Diya (C002)\n\nChurn Risk: HIGH\nRisk Score: 100/100\n\nKey Risk Factors:\n- Long inactivity period; Low recent order frequency; High support interaction; High discount dependency\n\nRecommendation:\nImmediate retention intervention\n\nPriority:\nP1\n'}), TraceEvent(iteration=0, event_type='AGENT_END', details={'status': 'COMPLETED'})])}